dune
libbinaryen.opam

These are some fixes that I believe will allow the opam-ci to pass on more platforms (we failed many on https://github.com/ocaml/opam-repository/pull/19961)
Closes #6
Closes #7

fix: Better handle various opam CI builds

---

.github/workflows/release.yml

Closes #4
I tested this locally and 2.0.3 seems to continue respecting the `OPAMYES=1` env var that is set by setup-ocaml.

fix(releaser): Pin opam-publish to 2.0.3

---

README.md

Closes #9 
Closes #12 (replaces it)
Since `@opam/conf-python-3` doesn't work with esy on Windows, I think we should just document this requirement (it is **generally** satisfied in the envs we require for Grain). Additionally, I'm planning to contribute upstream to binaryen to remove this python requirement entirely (ref https://github.com/WebAssembly/binaryen/issues/3036), but that will have to come in a later bump of this.

chore: Document dependencies & assumptions

---

.github/workflows/opam.yml

It doesn't work like 80% of the time (or 100% of the time right now).

chore: Drop Windows support in opam CI

---

dune

It seems that not all linux are marked as linux on opam-ci. We should always have a target for dllbinaryen.so (and I think we can assume it'll be built like linux).

fix: Always have a target on non-Windows/non-MacOS

---

dune

This bumps binaryen for the `version_103` tag. Doesn't seem like any other change is necessary.

feat!: Bump binaryen to version_103

---

.github/workflows/release.yml

GitHub removed `git://` support today: https://github.blog/2021-09-01-improving-git-protocol-security-github/
Switch to using `https://` for the initial clone so our release workflow works.

chore: Fix opam release workflow

---

.github/workflows/release.yml

This adds the ability for the releaser action to run on the v102 branch. This branch is created from the v102.0.0 tag so I can perform a bug fix related to the wasm-delegations.def file.

chore: Release on the v102 branch

---

dune

When trying to upgrade binaryen.ml, it failed because `wasm-delegations.def` couldn't be located.
The only way to really test this is with an esy resolution so I'm going to open a related PR over there.
Relies on #27 so I can trigger a release.

fix: Copy wasm-delegations.def into the correct location

---

dune

This ports our v102 fix to the main branch (which already tried to release a broken version of v103).
Closes #30

fix: Copy wasm-delegations.def into the correct location (#28)

---

.github/workflows/opam.yml
dune
libbinaryen.opam

This actually relies on fixes in `conf-python-3` and `conf-cmake` to land in the mingw repository, so draft for now.
This is all the changes to get this project working from opam on windows.

fix: Ensure project can build with Opam on Windows

---

.github/workflows/opam.yml
dune
libbinaryen.opam

This ports the v102 Windows + Opam fixes to our main branch, which is preparing a new v103 release that actually works.

fix: Ensure project can build with Opam on Windows (#33)

---

dune

This doesn't matter for most systems, but the opam CI failed on ubuntu 18.04 with an older cmake because the `-j4` wasn't passed through with `--` before it.

fix: Use double dash before -j4 to always pass through

---

README.md
test/config/flags.ml

These flags are sus and we should not recommend them.

chore: Remove flags that completely bork Mac M1

---

.github/workflows/js.yml
dune
test/types.js

Closes #59
This upgrades the project to version_108 of binaryen. This is the version that has our JS_OF_OCAML flag, so I also implemented the CI workflow to generate the JS file. The reason dune doesn't build it on demand is because we need emsdk to build the JS version and I don't want to force that upon people.
This did introduce a slight chicken-egg problem in that the JS file is generated at a different time as the rest of CI and so any changes aren't available to the esy or opam workflows. I could combine them if we think it is better, but I don't foresee this library changing much now that everything we needed was upstreamed. @ospencer do you have an opinion?

feat!: Update binaryen to version_108

---

.github/workflows/js.yml

I noticed that squashing into `main` resulted in a new commit of the binaryen.js file. This will avoid any changes on main from regenerating the file.

chore: Ignore rebuilding binaryen.js on pushes to main

---

.github/workflows/js.yml
dune

Binaryen seems to be failing to build in debian-11 CI runs on the opam repository. I'm trying to disable the `maybe-unitialized` error in GCC
Ref https://github.com/ocaml/opam-repository/pull/22337#issuecomment-1286556941

fix: Disable the maybe-uninitialized error in newer gcc

---

.github/workflows/esy.yml
.github/workflows/js.yml
.github/workflows/opam.yml
.github/workflows/release.yml

Had to drop the esy action because it doesn't seem to be maintained.
Closes #68

chore: Update workflows to avoid deprecation warnings

---

.github/workflows/release.yml

This upgrades release-please-action to utilize the fix in https://github.com/googleapis/release-please/releases/tag/v14.17.2 which solves the issue outlined in https://github.com/grain-lang/binaryen.ml/issues/164

chore: Upgrade to release-please-action that fixes issue linking

---

.github/workflows/esy.yml
.github/workflows/opam.yml
README.md
dune-project
dune-workspace
esy.lock/index.json
esy.lock/opam/chrome-trace.3.6.0/opam
esy.lock/opam/dune-build-info.3.6.0/opam
esy.lock/opam/dune-configurator.3.6.0/opam
esy.lock/opam/dune-rpc.3.6.0/opam
esy.lock/opam/dune.3.6.0/opam
esy.lock/opam/dyn.3.6.0/opam
esy.lock/opam/fiber.3.6.0/opam
esy.lock/opam/js_of_ocaml-compiler.4.1.0/opam
esy.lock/opam/menhir.20220210/opam
esy.lock/opam/menhirLib.20220210/opam
esy.lock/opam/menhirSdk.20220210/opam
esy.lock/opam/ordering.3.6.0/opam
esy.lock/opam/stdune.3.6.0/opam
esy.lock/opam/topkg.1.0.6/opam
esy.lock/opam/xdg.3.6.0/opam
esy.lock/overrides/opam__s__js__of__ocaml_compiler_opam__c__4.0.0_opam_override/package.json
libbinaryen.opam
package.json
test/dune

This upgrades binaryen to `version_110`
I also decided to drop support for dune 2 because dune 3 has a lot of QoL stuff for js_of_ocaml (like running tests in node by default)
Then, I realized that jsoo v4.1 was finally released, which has a optimizer fix that we need. So I set that as our minimum version... but then found that it isn't published in the mingw repository yet (so this is a draft currently).
Closes #50

feat!: Update binaryen to version_110

---

.github/workflows/opam.yml
dune

This updates the project to provide binaryen `version_111`. 
It also adds a gcc 10 job in CI to verify that the `maybe-uninitialized` flag isn't needed anymore. (You can see it failed when I applied it to `main`: https://github.com/grain-lang/libbinaryen/actions/runs/4098969417/jobs/7068455768)
I also dug into the other flag and found that we need it because esy ships gcc7 with mingw.

feat!: Upgrade to libbinaryen v111

---

.github/workflows/opam.yml

Attempting to cleanup some CI hacks with the newest version of setup-ocaml and the forked (and maintained?) mingw repository

chore(ci): Cleanup hacks in opam CI & update matrix to 4.14.1

---

.github/workflows/js.yml
.gitmodules

`binaryen-c.h` diff:
```diff
diff --git a/src/binaryen-c.h b/src/binaryen-c.h
index 07c116aec..f4f4f2d74 100644
--- a/src/binaryen-c.h
+++ b/src/binaryen-c.h
@@ -230,7 +230,7 @@ BINARYEN_API BinaryenFeatures BinaryenFeatureMemory64(void);
BINARYEN_API BinaryenFeatures BinaryenFeatureRelaxedSIMD(void);
BINARYEN_API BinaryenFeatures BinaryenFeatureExtendedConst(void);
BINARYEN_API BinaryenFeatures BinaryenFeatureStrings(void);
-BINARYEN_API BinaryenFeatures BinaryenFeatureMultiMemories(void);
+BINARYEN_API BinaryenFeatures BinaryenFeatureMultiMemory(void);
BINARYEN_API BinaryenFeatures BinaryenFeatureAll(void);
// Modules
@@ -2723,6 +2723,15 @@ BinaryenAddFunction(BinaryenModuleRef module,
BinaryenType* varTypes,
BinaryenIndex numVarTypes,
BinaryenExpressionRef body);
+// As …
```

feat!: Update to libbinaryen v115

---

.github/workflows/esy.yml
.github/workflows/js.yml
.github/workflows/opam.yml
.github/workflows/release.yml
esy.lock/index.json
esy.lock/opam/base.v0.17.1/opam
esy.lock/opam/js_of_ocaml-compiler.6.0.1/opam
esy.lock/opam/ocaml_intrinsics_kernel.v0.17.1/opam
esy.lock/opam/sexplib0.v0.17.0/opam
esy.lock/opam/stdio.v0.17.0/opam
libbinaryen.opam
package.json

This enables ocaml `5` with esy.
This adds the `setup-node` script to opam workflow as we need `node 22` when running the tests [see here](https://github.com/ocsigen/js_of_ocaml/issues/1845)
Based of: #112 
Closes: #88

feat!: Require node `>= 22` for jsoo `6`
